name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.1
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl: ^0.18.0
  template_string:
    git:
      url: https://github.com/dttrinh/flutter_sheet_localization
      path: template_string
