name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.5
  meta: ^1.8.0
  csv: ^5.0.1
  recase: ^4.0.0
  code_builder: ^4.4.0
  dart_style: ^2.0.0 
  source_gen: ^1.0.0
  flutter_sheet_localization:
    git:
      url: https://github.com/dttrinh/flutter_sheet_localization
      path: flutter_sheet_localization
  build: ^2.0.0
  analyzer: ^5.2.0
  collection: ^1.16.0
  intl: ^0.18.0
  localization_builder:
    git:
      url: https://github.com/dttrinh/flutter_sheet_localization
      path: localization_builder

dev_dependencies:
  build_test:
  build_runner:
